sample:
  Agalma-elegans_CWD116_100x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_100x.fastq
  Agalma-elegans_CWD116_090x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_090x.fastq
  Agalma-elegans_CWD116_080x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_080x.fastq
  Agalma-elegans_CWD116_070x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_070x.fastq
  Agalma-elegans_CWD116_060x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_060x.fastq
  Agalma-elegans_CWD116_050x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_050x.fastq
  Agalma-elegans_CWD116_040x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_040x.fastq
  Agalma-elegans_CWD116_030x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_030x.fastq
  Agalma-elegans_CWD116_020x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116_020x.fastq
  Chelophyes_CWD122_080x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_080x.fastq
  Chelophyes_CWD122_070x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_070x.fastq
  Chelophyes_CWD122_060x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_060x.fastq
  Chelophyes_CWD122_050x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_050x.fastq
  Chelophyes_CWD122_040x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_040x.fastq
  Chelophyes_CWD122_030x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_030x.fastq
  Chelophyes_CWD122_020x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122_020x.fastq
  Resomia_NA10_100x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_100x.fastq
  Resomia_NA10_090x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_090x.fastq
  Resomia_NA10_080x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_080x.fastq
  Resomia_NA10_070x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_070x.fastq
  Resomia_NA10_060x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_060x.fastq
  Resomia_NA10_050x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_050x.fastq
  Resomia_NA10_040x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_040x.fastq
  Resomia_NA10_030x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_030x.fastq
  Resomia_NA10_020x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Resomia_NA10_020x.fastq
  Cordagalma_CWD6_060x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Cordagalma_CWD6_060x.fastq
  Cordagalma_CWD6_050x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Cordagalma_CWD6_050x.fastq
  Cordagalma_CWD6_040x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Cordagalma_CWD6_040x.fastq
  Cordagalma_CWD6_030x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Cordagalma_CWD6_030x.fastq
  Cordagalma_CWD6_020x:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Cordagalma_CWD6_020x.fastq