sample:
  Agalma-elegans_CWD116:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Agalma-elegans_CWD116.fastq
  Chelophyes_CWD122:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Chelophyes_CWD122.fastq
  Cordagalma_CWD6:
    reads:
      - /gpfs/ysm/scratch60/dunn/cwd7/20221118_kmer_subsets/Cordagalma_CWD6.fastq